name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and Cypress
        run: npm run setup:cypress

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run